-- +goose Up
CREATE TABLE VIDEOS (
    id UUID PRIMARY KEY,
    userId UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    manimCode TEXT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMP NOT NULL DEFAULT NOW()
);

-- +goose Down
DROP TABLE VIDEOS;
