// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Name      string
	Password  string
	Email     string
	Createdat time.Time
	Updatedat time.Time
}

type Video struct {
	ID        uuid.UUID
	Userid    uuid.UUID
	Manimcode string
	Createdat time.Time
	Updatedat time.Time
}
