// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: video.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createVideo = `-- name: CreateVideo :one
INSERT INTO videos (id, userId, manimCode, createdAt, updatedAt)
VALUES ($1, $2, $3, NOW(), NOW())
RETURNING id, userid, manimcode, createdat, updatedat
`

type CreateVideoParams struct {
	ID        uuid.UUID
	Userid    uuid.UUID
	Manimcode string
}

func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, createVideo, arg.ID, arg.Userid, arg.Manimcode)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Manimcode,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const getAllVideos = `-- name: GetAllVideos :many
SELECT id, userid, manimcode, createdat, updatedat FROM videos
WHERE userId = $1
`

func (q *Queries) GetAllVideos(ctx context.Context, userid uuid.UUID) ([]Video, error) {
	rows, err := q.db.QueryContext(ctx, getAllVideos, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Manimcode,
			&i.Createdat,
			&i.Updatedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVideo = `-- name: GetVideo :one
SELECT id, userid, manimcode, createdat, updatedat FROM videos
WHERE id = $1 AND userId = $2
`

type GetVideoParams struct {
	ID     uuid.UUID
	Userid uuid.UUID
}

func (q *Queries) GetVideo(ctx context.Context, arg GetVideoParams) (Video, error) {
	row := q.db.QueryRowContext(ctx, getVideo, arg.ID, arg.Userid)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Manimcode,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}
